- example/dist/index.html
- example/src/App.tsx
- example/src/Code.module.scss
- example/src/Code.tsx
- example/src/Home.tsx
- example/src/Layout.module.scss
- example/src/Layout.tsx
- example/src/index.scss
- example/src/utils.tsx
- example/webpack.prod.cjs
- package-lock.json
- package.json
- src/KBarContextProvider.tsx
- src/KBarResults.tsx
- src/types.ts
- src/useStore.tsx
Closes #9 and.. a few other things
> feat: rework context provider

- src/KBarSearch.tsx
> chore: refocus input on root action change

- example/src/App.tsx
- src/index.tsx
- src/types.ts
- src/utils.ts
Closes #31.
Closes #14.
- Add optional icon, subtitle to `Action`
- Adds utility factory for creating actions
> feat: add optional icon, subtitle

- src/KBarResults.tsx
> Checking if action exists before calling perform

- example/src/App.tsx
- src/KBarResults.tsx
- src/KBarSearch.tsx
- src/index.tsx
- src/types.ts
- src/useStore.tsx
Closes #11.
https://user-images.githubusercontent.com/12195101/140184341-d7b1a44f-106e-4f9d-ae31-0be7277d7960.mp4
> feat: screen reader support

- example/src/App.tsx
- example/src/Blog.tsx
- example/src/Layout.tsx
- example/src/SearchDocsActions.tsx
> fix: ensure example imports from index

- example/src/App.tsx
- src/InternalEvents.tsx
- src/KBarAnimator.tsx
- src/KBarResults.tsx
- src/KBarSearch.tsx
- src/types.ts
Closes #93.
https://user-images.githubusercontent.com/12195101/140987530-fbdce8c1-0916-4084-b4f9-993fe49a706e.mp4
> feat: add external callbacks

- src/utils.ts
> fix: register touch event in outer click

- src/KBarSearch.tsx
Added a function parameter that allows adding a custom place holder.
Fix #149
> Added defaultPlaceholder

- src/InternalEvents.tsx
- src/types.ts
> Add disableDocumentLock option

- package-lock.json
- package.json
- src/InternalEvents.tsx
- src/tinykeys.ts
> feat: shortcuts rework

- src/KBarSearch.tsx
Added support for passing through `onKeyDown` in KBarSearch component
> Added support for passing through `onKeyDown` in KBarSearch component

- README.md
We are an [open source](https://github.com/omnivore-app/omnivore) read-it-later app. We've just started using kbar for our command palette.
> Add Omnivore.app to the used by section

- src/InternalEvents.tsx
> fix: prevent autofocus capture on first render

- package-lock.json
- package.json
- src/KBarPortal.tsx
> chore: replace reach portal

- README.md
We love Kbar at Fillout and https://tryapis.com!
> Add two new entries to "Used by"

- src/useStore.tsx
I think there are some typo at error msg
> chore: update error msg

- src/KBarAnimator.tsx
A very late PR related to the issue here - #248 
The motivation for this is clearly represented in the issue. Hence, skipping it here.
Would be happy to make any changes needed to get this merged.
> Again apologies for the extreme delay on making this PR. Slipped my mind and only noticed when I got a notification from the `stale-bot` marking the issue as stale
> feat: disableCloseOnOuterClick optional prop on KBarAnimator

- src/useMatches.tsx
Follow up to #325.
Adding a bit of type safety & memoization to our Fuse usage.
> chore: fuse cleanup

- src/KBarSearch.tsx
fix search input can not input chinese in react18 which use ReactDOM.createRoot to create app
> issue-327: fix search input can not input chinese

- src/KBarResults.tsx
https://github.com/user-attachments/assets/2d5654eb-c49e-4072-b91b-098df24b82d7
> fix: maintain active index on async registered actions
